name: main-portfolio
on:
  push:
    branches:
      - master

jobs:
  ktse:
    uses: ./.github/workflows/release.yml
    secrets:
      HARBOR_PASS: ${{ secrets.HARBOR_PASS }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    with:
      name: portfolio
      harborProject: "private"
      harborUser: "robot$portfolio"
      dockerFile: './Dockerfile'
      context: './'
      manifestFile: "./portfolio/portfolio.yml"
      repository: "kigawa01/k8s"
